Settings:
  #Chinese ChineseTW English Spanish
  language: English
  #Whether to check for new version
  check-update: true
  #Use MySQL or not
  mysql: false
  #TOP10 and the Server Total refresh time interval (Seconds)
  refresh-time: 300
  #Whether to enable cache correction
  #If you need to modify the data in the database directly, it is recommended to enable it
  #You need to note that cache-correction will not double verify the value of the amount in the process of deposit and withdraw
  #This function is not supported for non player account data
  cache-correction: false
  #Dose save transaction record
  #Only MySQL is supported
  transaction-record: true


#SQLite settings
SQLite:
  #Address is the folder path
  path: Default


#MySQL settings
MySQL:
  host: localhost:3306
  user: root
  pass: root
  database: data
  #auto add "_", can use %sign% to dicate Server ID (BungeeCord settings)
  table-suffix: ''
  encoding: utf8
  timezone: ''


#Connection pool settings
Pool-Settings:
  #use connection pool or not
  usepool: false
  maximum-pool-size: 10
  minimum-idle: 10
  maximum-lifetime: 180000
  idle-timeout: 60000


#BungeeCord settings
BungeeCord:
  #If you need to enable BC synchronization, please set in points.yml
  #After BungeeCord sync is turned on, the console and other plugins will not be able to modify the balance in the server without player
  #Please Set bungeecord to true in the spigot.yml
  #Server ID, keep the ID and the MySQL settings is the same between the servers requiring synchronization
  sign: aa